{
 "title": "Dashboard de Suportes",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": "select distinct  project_key from issues;"
   },
   {
    "name": "assignee",
    "label": "assignee",
    "query": "select distinct assignee_email from issues where project_key = '$project' and assignee_email != '';"
   },
   { "name": "issue_type", "label": "Jira Issue Type", "query": "FP Support, Support" }
  ]
 },
 "panels": [
  {
   "title": "Informações gerais sobre os tickets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total de tickets criados",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM issues\nWHERE \n  issue_type = '$issue_type'\n  AND project_key IN ('$project')\n  AND assignee_email IN ($assignee)\n  AND $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "# Tickets em aberto",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(*)\nfrom\n  issues\nwhere\n  status != 'Done'\n  and issue_type = '$issue_type'\n  AND $__timeFilter(created_at)\n  AND assignee_email IN ($assignee)\n  and project_key = '$project';"
    }
   ]
  },
  {
   "title": "# Tickets em backlog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM issues\nWHERE \n  status = 'To Do'\n  AND issue_type = '$issue_type'\n  and project_key = '$project'\n  AND $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "# Tickets em progresso",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(*)\nfrom\n  issues\nwhere\n  status = 'In Progress'\n  and issue_type = '$issue_type'\n  AND assignee_email IN ($assignee)\n  AND $__timeFilter(created_at)\n  and project_key = '$project';"
    }
   ]
  },
  {
   "title": "# Tickets com SLA violado",
   "type": "stat",
   "description": "Tickets com mais de 4 dias sem solução",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM\n  issues\nWHERE\n  created_at :: timestamptz < NOW() - INTERVAL '4 days'\n  and status not in ('Done')\n  and issue_type = '$issue_type'\n  AND assignee_email IN ($assignee)\n  and project_key = '$project';"
    }
   ]
  },
  {
   "title": "Total de tickets sem assignee",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM issues\nWHERE \n  issue_type = '$issue_type'\n  AND project_key IN ('$project')\n  AND assignee_email = ''\n  AND $__timeFilter(created_at);"
    }
   ]
  },
  {
   "title": "# tickets atendidos por responsável",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE \n    WHEN assignee_name IS NULL OR assignee_name = '' THEN 'unassignee'\n    ELSE assignee_name\n  END AS assignee_name,\n  COUNT(*) \nFROM issues\nWHERE\n  $__timeFilter(created_at)\n  AND project_key IN ('$project')\n  AND (assignee_email IN ($assignee) OR assignee_email IS NULL OR assignee_email = '')\n  AND issue_type = '$issue_type'\n  AND assignee_email != ''\nGROUP BY 1 \nORDER BY 2 DESC;\n"
    }
   ]
  },
  {
   "title": "Tickets abertos",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "select\n  key,\n  summary,\n  status,\n  assignee_name,\n  created_at,\n  updated_at\nfrom\n  issues\nwhere\n  status != 'Done'\n  and issue_type = '$issue_type'\n  and project_key = '$project'\n  \n  "
    }
   ]
  },
  { "title": "Métricas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Lead Time semanal",
   "type": "timeseries",
   "description": "Média por semana do tempo total entre a criação da issue e sua conclusão.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH changelogs AS (\n  SELECT\n    issue_id,\n    MIN(created_at :: timestamptz) AS done_at\n  FROM\n    issue_changelogs\n  WHERE\n    to_string = 'Done'\n  GROUP BY\n    issue_id\n),\nlead_times AS (\n  SELECT\n    i.id AS issue_id,\n    i.created_at :: timestamptz AS created_at,\n    c.done_at,\n    EXTRACT(\n      EPOCH\n      FROM\n        c.done_at - i.created_at :: timestamptz\n    ) / 3600 AS lead_time_hours\n  FROM\n    issues i\n    JOIN changelogs c ON i.id = c.issue_id\n  WHERE\n    i.issue_type = '$issue_type'\n    AND c.done_at IS NOT NULL\n    AND $__timeFilter(c.done_at)\n    AND assignee_email IN ($assignee)\n    AND project_key = '$project'\n)\nSELECT\n  date_trunc('week', done_at) AS week,\n  ROUND(AVG(lead_time_hours), 2) AS avg_lead_time_hours\nFROM\n  lead_times\nGROUP BY\n  week\nORDER BY\n  week;"
    }
   ]
  },
  {
   "title": "Cycle Time semanal ",
   "type": "timeseries",
   "description": "Média do tempo entre o início efetivo do trabalho (ex: quando a issue entra em \"In Progress\") até a sua conclusão",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH status_transitions AS (\n  SELECT\n    issue_id,\n    MIN(\n      CASE\n        WHEN to_string = 'In Progress' THEN created_at :: timestamptz\n      END\n    ) AS in_progress_at,\n    MIN(\n      CASE\n        WHEN to_string = 'Done' THEN created_at :: timestamptz\n      END\n    ) AS done_at\n  FROM\n    issue_changelogs\n  GROUP BY\n    issue_id\n),\ncycle_times AS (\n  SELECT\n    i.id AS issue_id,\n    s.in_progress_at,\n    s.done_at,\n    EXTRACT(\n      EPOCH\n      FROM\n        s.done_at - s.in_progress_at\n    ) / 3600 AS cycle_time_hours\n  FROM\n    issues i\n    JOIN status_transitions s ON i.id = s.issue_id\n  WHERE\n    i.issue_type = '$issue_type'\n    AND s.in_progress_at IS NOT NULL\n    AND s.done_at IS NOT NULL\n    AND $__timeFilter(s.done_at)\n    AND assignee_email IN ($assignee)\n    AND project_key = '$project'\n)\nSELECT\n  date_trunc('week', done_at) AS week,\n  ROUND(AVG(cycle_time_hours), 2) AS avg_cycle_time_hours\nFROM\n  cycle_times\nGROUP BY\n  week\nORDER BY\n  week;"
    }
   ]
  },
  {
   "title": "Throughput semanal ",
   "type": "timeseries",
   "description": "Quantos tickets chegaram em Done por semana",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH changelogs AS (\n  SELECT\n    issue_id,\n    MIN(created_at :: timestamptz) AS done_at\n  FROM\n    issue_changelogs\n  WHERE\n    to_string = 'Done'\n  GROUP BY\n    issue_id\n),\nissues_done AS (\n  SELECT\n    i.id AS issue_id,\n    c.done_at\n  FROM\n    issues i\n    JOIN changelogs c ON i.id = c.issue_id\n  WHERE\n    i.issue_type = '$issue_type'\n    AND $__timeFilter(c.done_at)\n    AND assignee_email IN ($assignee)\n    AND project_key = '$project'\n)\nSELECT\n  date_trunc('week', done_at) AS week,\n  COUNT(*) AS throughput\nFROM\n  issues_done\nGROUP BY\n  week\nORDER BY\n  week;"
    }
   ]
  },
  {
   "title": "Work In Progress (WIP) semanal",
   "type": "timeseries",
   "description": "Quantidade de issues que estavam em andamento (In Progress) em cada semana",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH status_transitions AS (\n  SELECT\n    issue_id,\n    MIN(CASE WHEN to_string = 'In Progress' THEN created_at::timestamptz END) AS in_progress_at,\n    MIN(CASE WHEN to_string = 'Done' THEN created_at::timestamptz END) AS done_at\n  FROM issue_changelogs\n  GROUP BY issue_id\n),\nfiltered_issues AS (\n  SELECT\n    i.id AS issue_id,\n    s.in_progress_at,\n    s.done_at\n  FROM issues i\n  JOIN status_transitions s ON i.id = s.issue_id\n  WHERE i.issue_type = '$issue_type'\n    AND s.in_progress_at IS NOT NULL\n    AND $__timeFilter(s.in_progress_at)\n    AND assignee_email IN ($assignee)\n)\nSELECT\n  date_trunc('week', gs.week) AS week,\n  COUNT(*) AS wip_count\nFROM filtered_issues i,\n  GENERATE_SERIES(\n    date_trunc('week', i.in_progress_at),\n    COALESCE(date_trunc('week', i.done_at - interval '1 day'), date_trunc('week', now())),\n    interval '1 week'\n  ) AS gs(week)\nWHERE $__timeFilter(gs.week)\nGROUP BY week\nORDER BY week;\n"
    }
   ]
  },
  {
   "title": "Tickets por dia",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', created_at::timestamp) AS day,\n  COUNT(*) AS total_fp_supports\nFROM\n  issues\nWHERE\n  issue_type = '$issue_type'\n  AND $__timeFilter(created_at::timestamp)\n  AND assignee_email IN ($assignee)\n  AND project_key = '$project'\nGROUP BY\n  day\nORDER BY\n  day;\n"
    },
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', created_at::timestamp) AS day,\n  COUNT(*) AS total_fp_supports\nFROM\n  issues\nWHERE\n  issue_type = '$issue_type'\n  AND $__timeFilter(created_at::timestamp)\n  AND assignee_email IN ($assignee)\n  AND project_key = '$project'\nGROUP BY\n  day\nORDER BY\n  day;\n"
    }
   ]
  },
  {
   "title": "Acumulo de tickets no periodo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', created_at::timestamp) AS day,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('day', created_at::timestamp)) AS cumulative_issues\nFROM\n  issues\nWHERE\n  issue_type = '$issue_type'\n  AND $__timeFilter(created_at::timestamp)\n  AND assignee_email IN ($assignee)\n  AND project_key = '$project'\nGROUP BY\n  day\nORDER BY\n  day;\n"
    },
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', created_at::timestamp) AS day,\n  SUM(COUNT(*)) OVER (ORDER BY DATE_TRUNC('day', created_at::timestamp)) AS cumulative_issues\nFROM\n  issues\nWHERE\n  issue_type = '$issue_type'\n  AND $__timeFilter(created_at::timestamp)\n  AND assignee_email IN ($assignee)\n  AND project_key = '$project'\nGROUP BY\n  day\nORDER BY\n  day;\n"
    }
   ]
  },
  {
   "title": "Tickets por dia",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('week', created_at::timestamp) AS day,\n  COUNT(*) AS total_fp_supports\nFROM\n  issues\nWHERE\n  issue_type = '$issue_type'\n  AND $__timeFilter(created_at::timestamp)\n  AND assignee_email IN ($assignee)\n  AND project_key = '$project'\nGROUP BY\n  day\nORDER BY\n  day;\n"
    },
    {
     "rawSql": "SELECT\n  DATE_TRUNC('week', created_at::timestamp) AS day,\n  COUNT(*) AS total_fp_supports\nFROM\n  issues\nWHERE\n  issue_type = '$issue_type'\n  AND $__timeFilter(created_at::timestamp)\n  AND assignee_email IN ($assignee)\n  AND project_key = '$project'\nGROUP BY\n  day\nORDER BY\n  day;\n"
    }
   ]
  }
 ]
}